### ISSUE TITLE
RTD no longer builds docs

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#150]
New builds fail, even for the existing master branch which used to build fine.

When allowing build to proceed with warnings, it looks like this:

![image](https://github.com/pybricks/pybricks-api/assets/12326241/e2662268-c6de-4b2c-bb29-2f69f1d0f31b)

May need to fix unsupported options for RTD, among other things.

```
preparing documents... WARNING: unsupported theme option 'style_external_links' given
WARNING: unsupported theme option 'logo_only' given
WARNING: unsupported theme option 'style_nav_header_background' given
done
```

**Comment by dlech** [comment]
It looks like it is not using the RTD theme. 

Probably due to https://github.com/pybricks/pybricks-api/blob/821a3e44555199c4d6b5da6803accef598d7222e/doc/common/conf.py#L148-L158

I guess RTD theme isn't the default anymore when build on readthedocs.org. so we should be able to just delete the if and leave the else clause.
