### ISSUE TITLE
Update to Sphinx 2.x (or 3.x) and RTD theme 0.5

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-api#20]
[sphinx_rtd_theme](https://github.com/readthedocs/sphinx_rtd_theme) v0.5.0 was just released today. This should fix many of the layout issues that prevented us from upgrading to Sphinx 2.x already.

I can't think of a specific example off the top of my head, but in the past there have been a few times where I was wishing we could take advantage of some new features.

**Comment by laurensvalk** [comment]
Archiving a few notes from an older issue:

Previously, we did not upgrade because the layout changed from 

![image](https://user-images.githubusercontent.com/12326241/105817785-5afabb00-5fb6-11eb-9cb9-3b2d6b32343b.png)

to 

![image](https://user-images.githubusercontent.com/12326241/105817795-5fbf6f00-5fb6-11eb-9a32-28e4376d64ea.png)

But this appears to have been fixed in the mean time :tada:

**Comment by laurensvalk** [comment]
Updating was fairly easy. Differences seem minimal. A few minor things noted so far:


Paragraph spacing between docstring paragraphs has changed.
(old vs. new)
![image](https://user-images.githubusercontent.com/12326241/105818159-d78d9980-5fb6-11eb-8209-6270c39fd4ce.png)
