### ISSUE TITLE
EV3Dev2 vs PyBricks2 APIs: are they converging or diverging going forward?

### ISSUE THREAD

**Issue by TheVinhLuong102** [pybricks/pybricks-api#22]
In my understanding, EV3Dev2 and PyBricks are the 2 most prominent Python libraries today for programming the EV3. I notice that both projects are progressing very ambitiously, with key persons such as @dlech active in both.

As a developer and a teacher (e.g. I'm teaching my son and several other young kids to program in Python using EV3 as the medium), I would like the understand the high-level future directions of these 2 major projects, in order to pick one as the primary API to teach. Do we have a plan to merge them in the future, or will they continue to develop separately to serve different audiences & needs?

(I am also asking the same question here https://github.com/ev3dev/ev3dev-lang-python/issues/745)

**Comment by WasabiFan** [comment]
The short answer: the ev3dev2 module and pybricks are independent, and new code should _probably_ use PyBricks unless there is particular functionality which is only available in ev3dev-lang-python.

That being said, I haven't been following PyBricks very closely and don't know what is/isn't supported or what the roadmap looks like. ev3dev2 has more overall coverage of the available APIs and interfaces offered directly by ev3dev.

To elaborate:

ev3dev-lang-python has been around since the early days of ev3dev; it is descended from an auto-generated wrapper around the C++ library. The module was split out from the C++ library and reimplemented in pure Python. From their origins, the ev3dev-lang-* family of repos were thin interfaces which more-or-less directly exposed the ev3dev driver APIs to the user. At the time,  this was "the" way of interacting with ev3dev devices, and the driver APIs were evolving sufficiently fast that it was more practical for me to automatically churn out these thin wrappers using scripts rather than make sure each edge-case was handled in JavaScript, Python, C++, and friends.

Since then, the ev3dev drivers have mostly stabilized, and our focus in ev3dev2 has shifted to creating _usable_ APIs. We implemented e.g. the motor pair classes for tank drive, steering, and joystick; easy ways to block waiting for an operation to complete; and better documentation all-around. So ev3dev2 supports every direct driver-provided property that ev3dev as a hardware interface supports, plus some ease-of-use classes and functions on top for more practical robots. It's a _good_ interface in many ways, but it also carries a large amount of baggage from its history.

David and Laurens started developing pybricks much more recently, with the aim of supporting other MINDSTORMS platforms which then also grew to include stock ev3dev (at least, based on my recollection). The pybricks interfaces are very well-designed, carefully-considered APIs for core robot programming, without the external signs of any particular driver design. As far as I know, everything that you really need is implemented here. There are some minor things which AFAIK are only available via ev3dev-lang-python (e.g. access to ev3dev's kernel-managed speed ramping, which may or may not be functional in the first place) but I suspect most use-cases don't have that issue.

If you do a search for ev3dev Python programs, the results are mostly going to be for ev3dev-lang-python; there are many of them out there. As pybricks grows, search results are probably going to get much more confusing before they get better. But as long as you use the official documentation and examples for either, you can get by.

---

I'd suggest waiting for an idea of roadmap and feature sets from @dlech or @laurensvalk, but I figure that should give a good general idea.

**Comment by TheVinhLuong102** [comment]
Wow, thanks so much @WasabiFan for the detailed history! This generally confirms my impressions that PyBricks aims to offer cleaner, more highly-abstracted APIs - less imperative, more "algorithmic" (although EV3Dev2 as of today is also very good, having almost attained parity with the visual LiveView / Scratch programming blocks).

I notice that @dlech @laurensvalk have very recently updated the https://github.com/pybricks/pybricks-projects tutorials, which look excellent when written in PyBricks 2.0. I'll hence make the shift to using PyBricks in my teaching going forward.

I look forward to more detail on the PyBricks roadmap by @dlech @laurensvalk. Thank you all very much for the great work.

**Comment by laurensvalk** [comment]
Thanks for your elaborate reply @WasabiFan, I think that covers it very well.

> I [...] don't know what is/isn't supported or what the roadmap looks like. 

- You can view the supported API [here](https://docs.pybricks.com/en/latest/).
- The Pybricks roadmap is [here](https://github.com/pybricks/support/issues/29).

> David and Laurens started developing pybricks much more recently, with the aim of supporting other MINDSTORMS platforms which then also grew to include stock ev3dev (at least, based on my recollection). The pybricks interfaces are very well-designed, carefully-considered APIs for core robot programming, without the external signs of any particular driver design. 

This is entirely correct. To add some more detail: Pybricks includes its own set of motor drivers so they could be used on all the embedded programmable hubs beyond EV3. This also allowed us to integrate drive base synchronization, and things like working ramping/acceleration and stall detection.

Historically, EV3 support for Pybricks mainly started because ev3dev was a lot easier to debug than the embedded hubs we were originally targeting. We could design high level control code, debug and datalog it extensively, and glue it back onto the more minimal embedded systems when we knew the high level things were stable. After a while though, it was natural step to include EV3 in the main roadmap. It is now quite fully-featured.

But a noteworthy advantage of ev3dev2 (and this will remain so), is that it can run with regular `python3`, which can be invaluable if you need certain Python libraries.

> are they converging or diverging going forward?

So to get back to the original question, I think they might continue to exist in parallel. EV3 support in Pybricks is essentially final, and we do currently not plan to change any of the API in a breaking way.

**Comment by TheVinhLuong102** [comment]
@laurensvalk thank you for the additional elaboration.

I have 2 follow-on questions:

1. Regarding non-EV3 Lego programmable hubs, such as the embedded hubs, the old NXT and the new SPIKE Prime, am I reading correctly that PyBricks intends to support all of them, while EV3Dev will continue to focus on the EV3 brick and its other "friends" such as the BrickPi & the PiStorms?

2. Is `python3` support in the PyBricks roadmap as well? If not, what is the constraint that creates this difference between PyBricks and EV3Dev?

**Comment by dlech** [comment]
Our primary focus for Pybricks will be the newer LEGO smart hubs. But if we have time or additional help we think Pybricks could run on the NXT too. Pybricks is strictly MicroPython and we don't have any plans to make it work with Python 3. It is more than enough work to just support one programming language. 😄

**Comment by TheVinhLuong102** [comment]
Thank you @dlech. I have a much better understanding of the direction of the ecosystem now. :) Let me close this issue then.
