### ISSUE TITLE
contentui plugin breaks anchor links

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-api#5]
On pages where we have "tabs" like this:

![image](https://user-images.githubusercontent.com/963645/77562545-24cc4680-6e8e-11ea-976b-4d3f7410aad1.png)

Links like https://docs.pybricks.com/en/latest/hubs.html#pybricks.hubs.MoveHub do not work because they are not on the default "tab". 

These links are used in search results, so search is broken for anything not on the default tab.

**Comment by laurensvalk** [comment]
Instead of doing it like this, I think we can just make them regular headings.

That's a bit more scrolling, but we could instead simplify in other ways. There's always the left-hand module menu.

Alternatively, @dlech suggested a breadcrumb menu, and/or we simply have a few hub icons at the top that take you to the right heading.

**Comment by laurensvalk** [comment]
Fixed by https://github.com/pybricks/pybricks-api/commit/938c62430f62cecc5e504d7bbc88e8c9c218de4a

Issues for improving navigation can be created separately.
