### ISSUE TITLE
Proper location for built-in functions and exceptions.

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-api#67]
`ubuiltins` is not a module and we can't import from it.

When we have autocomplete, it would be nice to have these functions and exceptions in the right place in the stubs API.

**Comment by dlech** [comment]
We can do like we did for `math`/`umath` if we want the module actually available on the hub as `ubuiltins` instead of `builtins`, but since there isn't a practical use case, I didn't do this yet. (Also see https://github.com/micropython/micropython/issues/7499).

I can't think of any better place than `ubuiltins` this could be in the stubs API as `builtins` would probably break some autocomplete tools. We don't have to mention the module name in the docs though if we don't want to.

**Comment by laurensvalk** [comment]
The main thing here is to make autocomplete in the stubs API work right; changing the implementation isn't critical to me. If `ubuiltins/__init__.py` is the right place for that, then let's keep it that way.

> We don't have to mention the module name in the docs though if we don't want to.

Indeed, this got a bit confusing along with that note about not importing from a nonexistent module. I've removed those references.

**Comment by dlech** [comment]
FWIW, the `builtins` module is real and can be imported in both Python and MicroPython (hence the note about not doing this).

```python
import builtins

print(dir(builtins))
```

**Comment by laurensvalk** [comment]
Agreed, but I'd prefer not to say how to not do things (unless it's about safety), as this can draw attention away from what people are really looking for. (That, and don't make forward references, or so my editor always told me :smile:)
